name-template: $NEXT_MINOR_VERSION 🌈
tag-template: $NEXT_MINOR_VERSION
version-template: $MAJOR.$MINOR
categories:
  - title: 🚨 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: fix
  - title: 📝 Documentation updates
    label: documentation
  - title: 🚦 Internal changes
    label: internal
exclude-labels:
  - reverted

template: |
  ## Changes
  $CHANGES
