version: 1
update_configs:
- package_manager: "java:maven"
  directory: "/"
  update_schedule: "weekly"

  default_reviewers:
    - "varyvol"
    - "fcojfernandez"
    - "oleg-nenashev"

  ignored_updates:
    - match:
        dependency_name: "jenkins-core"

- package_manager: "docker"
  directory: "/"
  update_schedule: "weekly"

  default_reviewers:
    - "varyvol"
    - "fcojfernandez"
    - "oleg-nenashev"
    
  ignored_updates:
    - match:
        dependency_name: "openjdk"
